language: python

sudo: required

python:
    - "2.7"

env:
    - CKANVERSION=master
    - CKANVERSION=2.7
    - CKANVERSION=2.6

install: bash travis/build.bash

script: bash travis/run.bash

after_success: coveralls

